---

name: Go Test

on: push

defaults:
  run:
    working-directory: Golang_test

env:
  GO111MODULE: on

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install PCAP for tests
      run: |
        sudo apt-get -y install libpcap-dev
      
    - name: Test
      run: go test -v
